### ISSUE TITLE
libLLVMHipSpvPasses.so: undefined symbol llvm::convertConstantExprsToInstructions

### ISSUE THREAD

**Issue by franz** [CHIP-SPV/chip-spv#102]
sometimes compilation fails with:

```
Consolidate compiler generated dependencies of target cuda-clock
[ 73%] Building CXX object samples/cuda_samples/CMakeFiles/cuda-clock.dir/0_Simple/clock/clock.cu.o
/gpfs/jlse-fs0/users/pvelesko/install/clang/clang14/clang14-spirv-omp/bin/opt: symbol lookup error: /home/pvelesko/space/CHIP-SPV/build/lib/libLLVMHipSpvPasses.so: undefined symbol: _ZN4llvm34convertConstantExprsToInstructionsEPNS_11InstructionEPNS_12ConstantExprEPNS_15SmallPtrSetImplIS1_EE
clang-14: error: unable to execute command: No such file or directory
clang-14: error: hipspv-link command failed due to signal (use -v to see invocation)
clang version 14.0.0 (/home/pvelesko/space/llvm-project/clang 2a2286e9859a518a46ead8e3ef5e283662766370)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/pvelesko/space/install/clang/clang14/clang14-spirv-omp/bin
clang-14: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [samples/cuda_samples/CMakeFiles/cuda-clock.dir/build.make:76: samples/cuda_samples/CMakeFiles/cuda-clock.dir/0_Simple/clock/clock.cu.o] Error 255
make[1]: *** [CMakeFiles/Makefile2:14446: samples/cuda_samples/CMakeFiles/cuda-clock.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

... at least two people reported the same symbol-missing error.

**Comment by franz** [comment]
Looking at the source code of Clang driver, it seems to invoke `opt` with absolute path, and the pass plugin is also an absolute path.

Possibly something in LD_LIBRARY_PATH makes Clang load the wrong library, in which case it's not our problem, but we could at least document it.

**Comment by pvelesko** [comment]
I had two versions of clang14 - one with openmmp and one without. The one without openmp worked fine whereas the openmp version gave me this error. Quite strange really since there shouldn't be any other differences between my installations

**Comment by franz** [comment]
@pvelesko do you still have the system and the clang14 installation where this happens ? can you try running the opt command with LD_DEBUG=all ? `LD_DEBUG=all .../path/to/opt [args...] 2>/tmp/opt.log` and then attach the log

**Comment by pvelesko** [comment]
I ran the following command which did not return any errors but the overall build still failed.
`LD_DEBUG=all /gpfs/jlse-fs0/users/pvelesko/install/clang/clang14/clang14-spirv-omp/bin/opt ./bitcode/BC/nearbyintD.bc -O3 -o ./test.bc 2>~/opt.log`
[opt.log](https://github.com/CHIP-SPV/chip-spv/files/9367642/opt.log)

@franz

**Comment by jbrodman** [comment]
I'm also running into this problem.

**Comment by franz** [comment]
@pvelesko  the opt command needs the plugin options: `-load-pass-plugin /path/to/chip_build_dir/lib/libLLVMHipSpvPasses.so -passes=hip-post-link-passes`, otherwise it just does normal LLVM optimizations.

**Comment by franz** [comment]
@jbrodman hi, do you also use OpenMP-enabled build of LLVM ? do you have multiple LLVM installations ?

**Comment by pvelesko** [comment]
````
LD_DEBUG=all /gpfs/jlse-fs0/users/pvelesko/install/clang/clang14/clang14-spirv-omp/bin/opt ./bitcode/BC/nearbyintD.bc -O3 -o -load-pass-plugin /path/to/chip_build_dir/lib/libLLVMHipSpvPasses.so -passes=hip-post-link-passes ./test.bc 2>~/opt.log 
````

[opt2.log](https://github.com/CHIP-SPV/chip-spv/files/9383405/opt2.log)

@franz

**Comment by jbrodman** [comment]
I just rebuilt w/o OpenMP - no help.

So I'm mucking around with this - it doesn't seem like libLLVMHipSpvPasses.so is actually linked against LLVM anywhere:
[15/270] : && /home/jbrodman/chip/install/bin/clang++ -fPIC -Wno-duplicate-decl-specifier -Wno-tautological-constant-compare  -Wno-c++20-extensions -Wno-un\
used-result -Wno-delete-abstract-non-virtual-dtor -Wno-deprecated-declarations -Wunused-command-line-argument -O3 -DNDEBUG   -shared  -o lib/libLLVMHipSpvP\
asses.so llvm_passes/CMakeFiles/LLVMHipPasses.dir/HipPasses.cpp.o llvm_passes/CMakeFiles/LLVMHipPasses.dir/HipDynMem.cpp.o llvm_passes/CMakeFiles/LLVMHipPa\
sses.dir/HipStripUsedIntrinsics.cpp.o llvm_passes/CMakeFiles/LLVMHipPasses.dir/HipDefrost.cpp.o llvm_passes/CMakeFiles/LLVMHipPasses.dir/HipPrintf.cpp.o ll\
vm_passes/CMakeFiles/LLVMHipPasses.dir/HipGlobalVariables.cpp.o llvm_passes/CMakeFiles/LLVMHipPasses.dir/HipTextureLowering.cpp.o llvm_passes/CMakeFiles/LL\
VMHipPasses.dir/HipAbort.cpp.o

Is this right? It seems like it ought to get linked against LLVM somehow.  The missing symbol can be found in libLLVMCore.a in my build of LLVM 15.

$ nm libLLVMCore.a | rg convertConstant
12090:0000000000000000 T _ZN4llvm34convertConstantExprsToInstructionsEPNS_11InstructionEPNS_12ConstantExprEPNS_15SmallPtrSetImplIS1_EE

**Comment by jbrodman** [comment]
Update: Yeah - think something is bad in the build configuration for chip-spv - it seems to be not linking against static libs that it should be.

I just rebuilt LLVM - but this time with -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON - previously I was using the default static lib build of LLVM - and.....

[270/270] Linking CXX executable samples/cuda_samples/cuda-reduction

Success!

**Comment by pvelesko** [comment]
>("Must define exactly one of HIP_PLATFORM_AMD, HIP_PLATFORM_NVIDIA or HIP_PLATFORM_SPIRV");
#error("Must define exactly one of HIP_PLATFORM_AMD, HIP_PLATFORM_NVIDIA or HIP_PLATFORM_SPIRV");

Would imply that something went terribly wrong with CMake configuration. Can you share your CMake configuration log? @jbrodman

**Comment by pvelesko** [comment]
@jbrodman `CHIP-SPV/build/CMakeCache.txt` + whatever output you get from running cmake configure

**Comment by franz** [comment]
> it doesn't seem like libLLVMHipSpvPasses.so is actually linked against LLVM anywhere

That is actually how the [LLVM manual](https://llvm.org/docs/CMake.html#developing-llvm-passes-out-of-source) on pass plugin development does it (without linking to LLVM):

`add_library(LLVMPassname MODULE Pass.cpp)`

> It seems like it ought to get linked against LLVM somehow.

I have tried to linking the plugin to libLLVMCore.a, and the problem is, that it also links in static global variables from libLLVMCore. Then when opt tries to load the plugin, it crashes because they conflict with the static global variables existing in the opt binary:

```
opt: CommandLine Error: Option 'enable-fs-discriminator' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/michal/0/LLVM_150_STATIC/bin/opt /tmp/hipmath-generic-link-19658d.bc -load-pass-plugin /tmp/build/lib/libLLVMHipSpvPasses.so -passes=hip-post-link-passes -o /tmp/hipmath-generic-lower-eae143.bc
```

After some more experiments, i have come up with an hacky workaround. I haven't found what's the official way of linking plugins to static LLVM builds. It's also possible that the problem is only related to this particular symbol (IOW a bug in LLVM).

**Comment by jbrodman** [comment]
[dump.txt](https://github.com/CHIP-SPV/chip-spv/files/9397674/dump.txt)
[CMakeCache.txt](https://github.com/CHIP-SPV/chip-spv/files/9397675/CMakeCache.txt)

**Comment by pvelesko** [comment]
@jbrodman very strange that things are not compiling for you. CMake looks good. This line `-- Generated HIP_OFFLOAD_COMPILE_OPTIONS: -D__HIP_PLATFORM_SPIRV__= -x hip --target=x86_64-linux-gnu -Xclang -no-opaque-pointers --offload=spirv64 -nohipwrapperinc --hip-path=/home/jbrodman/chip/hipinstall` defines the platform via this flag `-D__HIP_PLATFORM_SPIRV__` 

Can you try building again this time via `make VERBOSE=1` and paste the result please?

**Comment by jbrodman** [comment]
To be clear - I can build chip-spv itself now after finding out the LLVM shared lib issue. The build the tests step fails:

make build_tests_standalone (ninja build_tests_standalone)
[tests.txt](https://github.com/CHIP-SPV/chip-spv/files/9418263/tests.txt)

**Comment by pvelesko** [comment]
@jbrodman that doesn't look right.. it's missing the GPU offload string which was successfully generated in the previous step you sent me. 
Which distro are you using? 
Can you try a clean recursive clone before we dive deeper into investigating why it's failing?

**Comment by jbrodman** [comment]
Ubuntu 22.04. 

Sure.

**Comment by pvelesko** [comment]
closing since a workaround was implemented for the original issue. @jbrodman please open another ticket if you are still having issues building the tests.
