### ISSUE TITLE
Setting llvm-config should be enough to setup LLVM

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#133]
Referring to #96, I think the current way of relying to symlinks to the correct LLVM binaries calls for trouble as those symlinks can change over time. We should use the direct paths to LLVM binaries by default, and query that using the (given) llvm-config via -DLLVM_CONFIG in cmake.

**Comment by pvelesko** [comment]
@pjaaskel so instead of `cmake ../ -DCMAKE_CXX_COMPILER=/my/path/to/llvm14/clang++` do this: `cmake ../ -DLLVM_CONFIG=/my/path/to/llvm14/llvm-config-14.0.0` ?
