### ISSUE TITLE
Unable to build with clang-15 on Ubuntu 20.04 due to dependency on `icpx`

### ISSUE THREAD

**Issue by Slaedr** [CHIP-SPV/chip-spv#144]
I'm trying to build chip-spv on my Intel laptop (Core i7-1165G7, Ubuntu 20.04). I've built the spirv-llvm-translator using clang-15 and it seems to work. However, while building chip-spv, it fails with
```
[ 61%] Building CXX object samples/sycl_hip_interop/sycl_hip_interop_driver/CMakeFiles/sycl_chip_interop.dir/sycl_chip_interop.cpp.o
cd /home/v99/sources/chip-spv/build/samples/sycl_hip_interop/sycl_hip_interop_driver && icpx   -Wno-format-extra-args -fsycl -Wno-deprecated-declarations -std=c++17 -MD -MT samples/sycl_hip_interop/sycl_hip_interop_driver/CMakeFiles/sycl_chip_interop.dir/sycl_chip_interop.cpp.o -MF CMakeFiles/sycl_chip_interop.dir/sycl_chip_interop.cpp.o.d -o CMakeFiles/sycl_chip_interop.dir/sycl_chip_interop.cpp.o -c /home/v99/sources/chip-spv/samples/sycl_hip_interop/sycl_hip_interop_driver/sycl_chip_interop.cpp
/bin/sh: 1: icpx: not found
```
I tried to source my `/opt/intel/oneapi/setvars.sh`, but then it fails because of non-matching clang versions (Intel OneAPI 2022 appears to be using LLVM/Clang 11).
```
Unknown attribute kind (70) (Producer: 'LLVM15.0.1' Reader: 'LLVM 11.0.0')
clang: error: hipspv-link command failed with exit code 1 (use -v to see invocation)
```
Is there some workaround for this? Is icpx necessary for building/using chip-spv?

**Comment by pvelesko** [comment]
Did you source `setvars.sh` prior to running cmake? if not, try sourcing setvars first, then source llvm15 clang. Since setvars provides its own clang its likely that there is some conflict.

**Comment by pvelesko** [comment]
Could you please attach the CMake configuration log here?
