### ISSUE TITLE
Race condition when mixing synchronous and async memcopies

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#152]
We seem to have a race condition which can be reproduced at least with the test 
tests/catch/unit/memory/hipMemcpyAllApiNegative.cc:

```C++
  SECTION("hipMemcpyDtoDAsync half memory copy") {
    HIP_CHECK(hipMemcpyHtoD(hipDeviceptr_t(A_d), A_h,
                            (NUM_ELM * sizeof(float))/2));
    HIP_CHECK(hipMemcpyDtoDAsync(hipDeviceptr_t(B_d), hipDeviceptr_t(A_d),
                            (NUM_ELM*sizeof(float))/2,
                            stream));
    hipStreamSynchronize(stream); // <-- I added this.
    HIP_CHECK(hipMemcpy(B_h, B_d,
                        (NUM_ELM*sizeof(float))/2,
                        hipMemcpyDeviceToHost));
    HipTest::checkTest(A_h, B_h, NUM_ELM/2);
  }
```
I encountered this when testing with Intel CPU OpenCL (Issue #142). It doesn't appear with the GPU driver (maybe due to "excessive synchronization" of commands in its driver). The test manages to copy an undeterministic chunk of data in the hipMemcpyDtoDAsync() call before the hipMemcpy() gets executed and fails with various outputs depending where the async copy was. Adding that explicit synchronization call above fixes the race issue.

It's not completely explicit in the specs how the synchronizations should work when mixing the blocking and non-blocking memcpy calls, but I believe the non-blocking are assumed to synchronize the streams with other memcopies in flight. It's probably covered by some of these [rules here](https://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html#api-sync-behavior__memcpy-sync).

@Kerilk or @pvelesko have you encountered this or thought of proper sync solutions which do not kill asynch benefits?

**Comment by pvelesko** [comment]
> It doesn't appear with the GPU driver (maybe due to "excessive synchronization" of commands in its driver)

Can you elaborate on what you mean by this?

> but I believe the non-blocking are assumed to synchronize the streams with other memcopies in flight

did you mean blocking calls here? As in, we expect `hipMemcpy` to sync because there is an outstanding memcopy. Since hipMemcpy (blocking) doesn't seem to do that, we have to put the `hipStreamSynchronize()` prior to calling it.

**Comment by pvelesko** [comment]
> have you encountered this

No, haven't encountered this yet. 

>  or thought of proper sync solutions which do not kill asynch benefits?

What if inside the `hipMemcpy` call we first check to see if there are any outstanding `hipMemcpyAsync` calls and if so, we wait until those complete prior to performing the memcopy? Additionally, we could check if the memory regions between the current call and outstanding calls overlap and if not, then skip the wait?

**Comment by Sarbojit2019** [comment]
@pjaaskel, It is not really memcpy rules but it is the behavior of default null stream.

hipMemcpy is a sync call on default nullstream and nullstream does automatic sync to all **active blocking streams**. In other words runtime will wait for any pending work on all active blocking stream before submitting anything to nullstream, be it kernel or copy operation. If CHIP_SPV is not doing it today we should do that. 
Behavior changes if custom stream is non-blocking or default stream is a per-thread default stream.

Below is a good article on cuda behavior of default null stream vs per thread null stream.
https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html#stream-sync-behavior__default-stream

**Comment by pvelesko** [comment]
Ah 

> In other words runtime will wait for any pending work on all active blocking stream before submitting anything to nullstream, be it kernel or copy operation

We gather all blocking streams and their respective `LastEvent` and then create a barrier with those `LastEvent`s as the dependencies. 

So in this case, `hipMemcpy` should not execute until `hipMemcpyAsync` has finished.

**Comment by pjaaskel** [comment]
> @pjaaskel, It is not really memcpy rules but it is the behavior of default null stream.
> 
> hipMemcpy is a sync call on default nullstream and nullstream does automatic sync to all **active blocking streams**. In other words runtime will wait for any pending work on all active blocking stream before submitting anything to nullstream, be it kernel or copy operation. If CHIP_SPV is not doing it today we should do that. Behavior changes if custom stream is non-blocking or default stream is a per-thread default stream.
> 
> Below is a good article on cuda behavior of default null stream vs per thread null stream. https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html#stream-sync-behavior__default-stream

Thanks for the info. So my local temporary fix of just calling hipDeviceSynchronize() inside hipMemcpy() is not too far off what is actually required here and should not break semantics, right? What @pvelesko proposes could be an optimization to reduce needless synchronization which we could implement later. Unless someone wants to take a stab on it earlier?

**Comment by pvelesko** [comment]
@pjaaskel In my first message completely forgot about stream semantics. What I am saying is that queue semantics are enforced and the error you are seeing should not happen. Perhaps the HIP unit tests are lacking and there is a bug in the `syncQueues` method?

**Comment by pjaaskel** [comment]
@pvelesko OK. can you check? My current local workaround is pretty brutal.

**Comment by pvelesko** [comment]
@pjaaskel if there was a bug in `syncQueues` then I would imagine a lot more tests would fail. I disabled queue syncronization and indeed a bunch of tests fail/timeout indicating that without calls to `syncQueues` things fall apart.

I guess I should build for the OpenCL CPU because this error is not reproducible on GPUs it seems?

**Comment by pjaaskel** [comment]
I would not generalize that much. Race conditions are so random and affected by many things. "GPUs" that work might just over-synchronize and it then hides some of the race conditions as a coincidence. This seems to be a corner case where async and sync commands are mixed.

**Comment by pvelesko** [comment]
How do you suggest we approach fixing this issue?

**Comment by pjaaskel** [comment]
If you have an idea for a better solution than my brutal sync devices in hipMemCpy then could you implement it? Yes you are right it might currently require Intel OpenCL CPU for reproducing as I didn't encounter it so far with other platforms. 

My comment above was meant more generally: We have to assume we will bump into it with some other platforms in the future if not tackled and I suspect there might be other related issues that might pop up later, but are just hidden by luck.

**Comment by pvelesko** [comment]
Are there any other OpenCL CPU runtimes we can try to see if this error persists?

**Comment by pjaaskel** [comment]
Soon hopefully PoCL works adequately (@franz is on it). It could work well enough to reproduce test case too, I haven't tested yet.

**Comment by Sarbojit2019** [comment]
@pjaaskel, I don't think calling device sync inside hipMemcpy is a right approach as it will wait for all active streams(including non-locking) to complete tasks on the device which is not an expected behavior. Property of a Non-blocking stream is to not  blocked on any other operation going on other streams.

**Comment by pjaaskel** [comment]
Yes, I agree it's not optimal, but I believe it should not _break_ anything (expect performance for workloads that rely on asynch execution). Let's hope we can find a better solution than this.

**Comment by pjaaskel** [comment]
@Sarbojit2019: Can you add here an example where extra synchronization (flushing/syncing all streams at blocking memcpy) will actually break semantics? Is there a deadlock situation possible? I'm not familiar with the CUDA async/blocking semantics, I just want to understand the problem overall. If there are async streams, their kernel finish times should be undefined by default, so if we block on a blocking call and as a side effect wait until the other streams finish, it's just one possible finish order for those async queues, but is there a case the application side could rely on the finish order? Event dependencies somehow? 

Similar OpenCL case would be if we have a command queue with async commands in it and then push a blocking command to it and that (as an internal consequences) clFinish() all the commands before it proceeds. Brutal, but should not break application semantics as far as I understood as the CQs are acyclic.

**Comment by Sarbojit2019** [comment]
@pjaaskel, Cuda, HIP both has given option to create two kind of user streams i) blocking and ii) non-blocking. Blocking stream always does **implicit synchronization with null stream**. On the other hand **non-blocking stream does not do any implicit synchronization with null stream**. See the highlighted(yellow) portion in the image captured from cuda spec   
![image](https://user-images.githubusercontent.com/52556743/192488698-27a1bda4-b081-45a7-84f4-5550e9898a0c.png)

Coming to the proposal, putting device level sync during copy will force non-blocking stream to finish anything is in flight which can create issues. It can be expected behavior mismatch, performance drop, or functional issues.

**Comment by pjaaskel** [comment]
Yes, I agree there will be a performance drop due to reduced parallelism, but the functional/behavioral problems I still don't. The wording is **may** run concerruntely, just wondering what are the breaking cases. Anyhow, I understood @pvelesko is checking for a better solution so this is not just relevant. I just have a curious mind that's all ;)

**Comment by pvelesko** [comment]
> Yes, I agree there will be a performance drop due to reduced parallelism, but the functional/behavioral problems I still don't understand

A test like this would fail: 
```
hipStreamCreate(&myNonBlockingStream, hipStreamNonBlocking);
hipMemcpyAsync(..., myNonBlockingStream); 
hipKernelLaunchGLL(...., myNonBlockingStream); // long running kernel
hipMemcpy(....); // brutal fix executes a queue finish() on myNonBlockingStream
assert(hipStreamQuery(myNonBlockingStream) == hipErrorNotReady); // no explicit sync, we are expecting the queue to still be executing the kernel
```

> Anyhow, I understood @pvelesko is checking for a better solution

yes.

**Comment by pjaaskel** [comment]
@pvelesko that example doesn't seem right. Are you expecting something based on the execution timing of the "long running kernel"? Seems very racy and undefined end result to me. What if you run the same program on a new GPU which happens to finish the kernel earlier than the hipMemcpy finishes - the same (legal) end result?

Based on quick reading of https://developer.nvidia.com/blog/gpu-pro-tip-cuda-7-streams-simplify-concurrency/ it seems indeed we _can_ sync here and the observer (host program) just sees an earlier finish of the kernel than expected, but should be still within defined outcomes as the host should not assume anything on the execution times (explicit synchronization is needed for valid deterministic outcomes).

**Comment by pvelesko** [comment]
> Are you expecting something based on the execution timing of the "long running kernel"? 

yes - we are expecting the kernel to still be running when the regular memory copy finishes. There are multiple unit tests that depend on this. That's how AMD wrote the unit tests.

> What if you run the same program on a new GPU which happens to finish the kernel earlier than the hipMemcpy finishes - the same (legal) end result?

Then the test breaks. We've had to adjust test sizes because of this. If we could execute a `sleep()` inside the kernel then it wouldn't be as flaky. 

> it seems indeed we can sync here

Nothing is stopping us from putting a sync whereever we want but putting a sync inside the `hipMemcpy` would break the expected queue semantics.

**Comment by pjaaskel** [comment]
I consider these test cases invalid if they assume/rely on the finish order of concurrently executing tasks based on expected execution times. They are then testing a particular implementation&platform, not the spec wording. I'd say we keep skipping such fragile tests as flaky and focus on proper test cases which do not rely on particular implementation.  Can you point me to those? I'll take a quick look what could be done with them.

**Comment by pvelesko** [comment]
> I'd say we keep skipping such fragile tests as flaky

we don't skip these tests at all currently. It's very important that we have proper queue semantics. How would you test this if not by relying on long-running kernels/operations? 

> They are then testing a particular implementation&platform, not the spec wording

I disagree here - they are testing the spec but you are right that such tests can be affected by specs of the system you're running on.

> Can you point me to those? I'll take a quick look what could be done with them. 

I don't have a comprehensive list but it's probably a lot. Look at the Catch2 unit tests.  Probably any test that uses non-blocking streams. Also, samples.

**Comment by pjaaskel** [comment]
I agree it's important we take advantage of parallelism, but concurrent safety and correctness must come first.

The CUDA spec wording says "things _may_ execute in parallel" whether they _will_ so so depends on various things (the HW, implementation, other parallel workloads, etc.). So from the ground up such tests are rather flaky although they might work for now on the current hardware for most of the time. It's somehow bothering to me to have such tests on a multi-platform implementation test suite which is expected to work by default. But it's just my opinion.

**Comment by pvelesko** [comment]
> I agree it's important we take advantage of parallelism, but concurrent safety and correctness must come first.


It's important that we follow the spec. Putting in a device synchronization breaks compliance. I agree with you that we should focus on correctness first. 

> The CUDA spec wording says "things may execute in parallel" whether they will do so depends on various things (the HW, implementation, other parallel workloads, etc.)


by putting a device sync it becomes the case that things MAY NOT execute in parallel - breaking compliance with the spec. 

> It's somehow bothering to me to have such tests on a multi-platform implementation test suite which is expected to work by default. But it's just my opinion.


I agree that it's not optimal but I am still eager to hear a better solution. 

I just did a quick test of putting a device sync inside the `hipMemcpy` with the following tests failing (more tests failed but those failures unrelated)


```
Total Test time (real) = 1018.36 sec

The following tests FAILED:
	176 - Unit_hipMemset2DAsync_MultiThread (Timeout)
	510 - Unit_hipStreamAddCallback_MultipleThreads (Timeout)
	513 - Unit_hipStreamAddCallback_WithCreatedStream (Timeout)
	579 - Stress_hipMalloc (Failed)
	585 - activemask (Failed)
	655 - cuda-simpleCallback (Timeout)
```

**Comment by pjaaskel** [comment]
A better solution here IMHO would be just isolate those tests that are testing a particular implementation and which might fail even if the implementation follows what's written in the specs (e.g. finish the said command faster than expected from the point of view of the perceiver). 

Thanks, I'll take a look at these tests.

**Comment by pjaaskel** [comment]
#162
