### ISSUE TITLE
fatal: No url found for submodule path 'HIPCC' in .gitmodules

### ISSUE THREAD

**Issue by linehill** [CHIP-SPV/chip-spv#159]
Submodule updates with following command fails on the main branch (482cdba).
```bash
$ git submodule update --init --recursive 
fatal: No url found for submodule path 'HIPCC' in .gitmodules
```

**Comment by linehill** [comment]
I was able to fix this issue locally by issuing `git rm --cached HIPCC` and then `git submodule update --init --recursive`.

**Comment by linehill** [comment]
Fixed the issue locally by reverting this commit: c092be8.

**Comment by pvelesko** [comment]
That was supposed to be no-op... Thanks for root-causing. Fixed in main.
