### ISSUE TITLE
No url found for submodule path 'HIPCC' in .gitmodules

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#161]
```
git clone https://github.com/CHIP-SPV/chip-spv.git chip-spv-rls -b Release-0.9
cd chip-spv-rls
git submodule update --init --recursive
Submodule 'HIP' (https://github.com/CHIP-SPV/HIP.git) registered for path 'HIP'
fatal: No url found for submodule path 'HIPCC' in .gitmodules
```
Is this something you are working on @pvelesko in the main branch and unintentionally affecting the release branch?

**Comment by linehill** [comment]
I encountered this on the main branch https://github.com/CHIP-SPV/chip-spv/issues/159. Reverting the following commit fixes the issue: c092be83166eaa90ca84cbde03358efc4ddc8974.

**Comment by pvelesko** [comment]
mistake was made in Release-0.9 branch which was merged into main. same as #159 

@linehill please merge the revert into Release-0.9 and close this ticket.

**Comment by linehill** [comment]
Should be fixed now.
