### ISSUE TITLE
Failing tests with Intel iGPU and its OpenCL driver

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#164]
With export OverrideDefaultFP64Settings=1 and export IGC_EnableDPEmulation=1 to emulate the doubles (#137).

Check the end of the thread for the current status.

**Comment by pjaaskel** [comment]
With #162:
```
The following tests FAILED:
	173 - Unit_hipMemcpyWithStream_MultiThread (Subprocess aborted)
	500 - Unit_hipStreamGetFlags_BasicFunctionalities (Failed)
	571 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	572 - Unit_hipStreamPerThread_DeviceReset_1 (Subprocess aborted)
	579 - Stress_hipMalloc (Failed)
Errors while running CTest

```

**Comment by pjaaskel** [comment]
With #162, now down to

```
The following tests FAILED:
	500 - Unit_hipStreamGetFlags_BasicFunctionalities (Failed)
	571 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	572 - Unit_hipStreamPerThread_DeviceReset_1 (Subprocess aborted)
```

**Comment by pvelesko** [comment]
interesting.. same ones as #146

**Comment by pjaaskel** [comment]
Yep, seems like heap corruption, overwriting the malloc() book keeping structures or such. Could be serious. Have you ran valgrind recently?

**Comment by pvelesko** [comment]
I can't reproduce this on the OpenCL iGPU. On the OpenCL CPU side, the error seems to be coming from the OpenCL runtime since the test passes but it segfaults upon thread exit. @pjaaskel

**Comment by pjaaskel** [comment]
It might be coming from or just appear in it (memory corruption can be visible that way). It fails for both iGPU and the CPU here, but we can postpone for 0.9.1.

**Comment by pjaaskel** [comment]
With the latest OpenCL fixes @pvelesko, this target regressed by one test:

```
The following tests FAILED:
	150 - Unit_hipMemset3DAsync_ConcurrencyMthread (Subprocess aborted)
	571 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	572 - Unit_hipStreamPerThread_DeviceReset_1 (Subprocess aborted)
Errors while running CTest
``

**Comment by pvelesko** [comment]
ok let me check this.

**Comment by pjaaskel** [comment]
With the latest 0.9 branch:

```
	173 - Unit_hipMemcpyWithStream_MultiThread (SEGFAULT)
	571 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	572 - Unit_hipStreamPerThread_DeviceReset_1 (SEGFAULT)
```

**Comment by pvelesko** [comment]
````
	571 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	572 - Unit_hipStreamPerThread_DeviceReset_1 (SEGFAULT)
``` 

are already root-caused waiting a fix from Intel. 

```
	173 - Unit_hipMemcpyWithStream_MultiThread (SEGFAULT)
```

Also seems like a bug in OpenCL runtime - need to make a C reproducer.

**Comment by pjaaskel** [comment]
OK. Did you report the issues to https://github.com/intel/compute-runtime/issues?

**Comment by pvelesko** [comment]
@pjaaskel  https://github.com/CHIP-SPV/chip-spv/issues/146 https://github.com/intel/compute-runtime/issues/568

**Comment by pjaaskel** [comment]
That's for Level Zero, this is OpenCL, but maybe the same underlying issue.

**Comment by pvelesko** [comment]
läpällä ja kännissä

**Comment by pjaaskel** [comment]
At 3 failing tests with https://github.com/CHIP-SPV/chip-spv/commit/7f2061394981f069f1b3a3a1f52558b095ffbec3.
```
	 21 - stream (Failed)
	658 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	659 - Unit_hipStreamPerThread_DeviceReset_1 (Subprocess aborted)
```

**Comment by pvelesko** [comment]
@pjaaskel I can only reproduce the `stream` failure one of the systems at JLSE. It's not reproducible on the system which has the most stable runtime. I was told to use this system as reference.

**Comment by pjaaskel** [comment]
OK, let's see if it goes away with future driver upgrades.

**Comment by pjaaskel** [comment]
Wrong issue, but thanks. We might use them for Intel targets if it works although it doesn't seem to be an extension.

**Comment by pjaaskel** [comment]
None of the 688 or so fail here anymore with OpenCL/iGPU. Well done!

**Comment by pjaaskel** [comment]
Looking good still, but one of the tests is time outing:
``
...
99% tests passed, 1 tests failed out of 692

Label Time Summary:
cuda        =  63.15 sec*proc (27 tests)
internal    = 116.91 sec*proc (85 tests)

Total Test time (real) = 960.48 sec

The following tests did not run:
	 65 - sycl_chip_interop (Skipped)
	 66 - sycl_chip_interop_usm (Skipped)

The following tests FAILED:
	620 - Unit_hipStreamCreate_MultistreamBasicFunctionalities (Timeout)
Errors while running CTest
```

**Comment by pjaaskel** [comment]
Current (6407148b872) status:
```
99% tests passed, 7 tests failed out of 757
...
The following tests FAILED:
	376 - Unit_hipGraphNodeGetType_Functional (Failed)
	377 - Unit_hipGraphNodeGetType_NodeType (Failed)
	753 - ABM_AddKernel_MultiTypeMultiSize - int (Failed)
	754 - ABM_AddKernel_MultiTypeMultiSize - long (Failed)
	755 - ABM_AddKernel_MultiTypeMultiSize - float (Failed)
	756 - ABM_AddKernel_MultiTypeMultiSize - long long (Failed)
	757 - ABM_AddKernel_MultiTypeMultiSize - double (Failed)
Errors while running CTest

```

```
"Unit_hipGraphExecHostNodeSetParams_Negative" start time: Jan 16 15:08 EET
Output:
----------------------------------------------------------
CHIP error [TID 54506] [1673874492.764718369] : hipErrorInvalidValue (Failed to find the node in hipGraphExec_t) in /home/pjaaskel/src/chip$

CHIP error [TID 54506] [1673874492.764815782] : Caught Error: hipErrorInvalidValue
CHIP error [TID 54506] [1673874492.764901796] : hipErrorInvalidValue (Failed to find the node in hipGraphExec_t) in /home/pjaaskel/src/chip$

CHIP error [TID 54506] [1673874492.764910125] : Caught Error: hipErrorInvalidValue
CHIP error [TID 54506] [1673874492.764956995] : hipErrorInvalidValue (Failed to find the node in hipGraphExec_t) in /home/pjaaskel/src/chip$

CHIP error [TID 54506] [1673874492.764964494] : Caught Error: hipErrorInvalidValue
Filters: Unit_hipGraphExecHostNodeSetParams_Negative

```

The ABM cases fail due to pushing too large WG size (1000) while the iGPU has 512 max.

**Comment by pjaaskel** [comment]
Let's open separate issues to each test we start to fix and assign them to whoever's working on it to keep better track.
