### ISSUE TITLE
cuspvc expects hipcc to be in PATH? 

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#168]
```
585/667 Test #585: activemask ................................................................***Failed  Required regular expression not found. Regex=[error: '__activemask' is unavailable: unsupported in CHIP-SPV
]  0.00 sec
/home/pvelesko/space/CHIP-SPV/build/bin/cuspvc: line 33: hipcc: command not found
```

**Comment by linehill** [comment]
It looks for `hipcc` from `PATH` with additional search locations in it (see `<chip-spv>/bin/cuspvc-{build,install}.in`). The reason the test fails is because the `hipcc` is relocated and renamed in the build directory.

**Comment by pjaaskel** [comment]
@linehill are you able to fix this quickly? We want to tag the release in a few hours.

**Comment by linehill** [comment]
PRs for the fix are ready.

**Comment by linehill** [comment]
Nevermind, those PRs went for milestone 1.0.

**Comment by linehill** [comment]
Is the `Release-0.9` branch the correct one? I ran the test and it is passing on my machine.

**Comment by pvelesko** [comment]
yes that's the correct branch. Maybe update your submodules?

**Comment by linehill** [comment]
Updated to target milestone 1.0 (assuming it's fine).
