### ISSUE TITLE
Failing tests with Intel iGPU and its L0 driver

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#170]
The following test fails on iGPU in main, Release-0.9, and OpenCLFixes branches. 
```
	550 - Unit_hipEvent (Subprocess aborted)
```

it also fails on discrete GPUs up until you load the latest runtime 519 where this issue gets fixed.

**Comment by pvelesko** [comment]
@pjaaskel should this be marked as flaky?

**Comment by pjaaskel** [comment]
Not sure if necessary as you documented the fix here (runtime 519)?

**Comment by pvelesko** [comment]
No fix for iGPU

**Comment by pjaaskel** [comment]
OK, then flaky is a good idea. But OTOH not all of those remaining CPU/GPU OpenCL failures are marked flaky and the testers should find those known issues by searching the issues?

**Comment by pjaaskel** [comment]
I'd say flaky = test case that "sometimes passes, sometimes doesn't".
