### ISSUE TITLE
Setup CI bots which test pull requests

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#171]
Can we setup such automatism for the targets of interest to make branch testing sensible?

**Comment by pvelesko** [comment]
This has been discussed previously and it's complicated. AMD doesn't want to test Intel systems and vice versa. Intel HW not available, latest SDKs not public. Argonne can't have remote services triggering runs.

Honestly I think the best solution would be if I host a test bed. I just need to get all the HW together and setup CI. With Intel GPUs available for purchase now/soon, I think this is very doable.

It would be amazing - testing has been a time hog.

**Comment by pjaaskel** [comment]
Yep, let's see how it will be in the near future with the HW availability. Buildbot was nice with its master-slave mechanism as slaves could be hosted by anyone privately, I don't know of the other CI systems.
