### ISSUE TITLE
[Stream Semantics]hipStreamSynchronize synchronizes all other streams

### ISSUE THREAD

**Issue by Sarbojit2019** [CHIP-SPV/chip-spv#173]
**Tests Scenarios** : hipStreamSynchronize(stream1) should not synchronize stream2. hipStreamQuery(stream2) should return hipErrorNotReady.

**Experiment** : Stream1 is programmed with task of 2 sec long and stream2 got 10sec long task. Hence synchronize call to stream1 should let stream1 to finish but in this case it is forcing stream2 as well. See the output pasted below...

```
#include <hip/hip_runtime.h>
#include <unistd.h>

void callback_sleep2(hipStream_t stream, hipError_t status, void* user_data) {
    int *data = (int*)user_data;
    printf("callback_sleep2: Going to sleep for 2sec\n");
    sleep(2);
    *data = 2;
    printf("callback_sleep2: exiting now\n");
}

void callback_sleep10(hipStream_t stream, hipError_t status, void* user_data) {
    int *data = (int*)user_data;
    printf("callback_sleep10: Going to sleep for 10sec\n");
    sleep(10);
    *data = 2;
    printf("callback_sleep10: exiting now\n");
}

int main() {
    int* stream1_shared_data = nullptr;
    int* stream2_shared_data = nullptr;
    stream1_shared_data = (int*)malloc(sizeof(int));
    stream2_shared_data = (int*)malloc(sizeof(int));
    hipStream_t stream1, stream2;
    hipStreamCreate(&stream1);
    hipStreamCreate(&stream2);

    *stream1_shared_data = 1;
    hipStreamAddCallback(stream1, callback_sleep2, stream1_shared_data, 0);
    *stream2_shared_data = 1;
    hipStreamAddCallback(stream2, callback_sleep10, stream2_shared_data, 0);

    printf("Going to sync stream1\n");
    hipStreamSynchronize(stream1);
    printf("Going to call query\n");
    printf("stream2 status %s\n", hipGetErrorName(hipStreamQuery(stream2)));

    hipDeviceSynchronize();
    if (*stream1_shared_data != 2 || *stream1_shared_data != 2) {
        printf("failed\n");
    } else {
        printf("passed\n");
    }

    return 0;
}
```
**output:**
Going to sync stream1
callback_sleep2: Going to sleep for 2sec
callback_sleep2: exiting now
callback_sleep10: Going to sleep for 10sec
callback_sleep10: exiting now
Going to call query
stream2 status **hipSuccess**  <- expectation is it should return hipErrorNotReady.

**Comment by pvelesko** [comment]
Can you please make a branch so that I can test right away instead of having to copy-paste code @Sarbojit2019

**Comment by pvelesko** [comment]
Please try the following and let me know 
```
hipError_t hipStreamSynchronize(hipStream_t Stream) {
  CHIP_TRY
  CHIPInitialize();

  Stream = Backend->findQueue(Stream);
  Backend->getActiveDevice()->getContext()->syncQueues(Stream); // comment out this line
  Stream->finish();
  RETURN(hipSuccess);

  CHIP_CATCH
}
```

**Comment by Sarbojit2019** [comment]
@pvelesko, suggested change did not help. BTW, I have raised the PR #174 take a look.
I looked further and noticed hipStreamQuery never returns hipErrorNotReady (even when hipStreamSynchronize line is commented)

```
.....
    printf("Going to sync stream1\n");
    **//hipStreamSynchronize(stream1);**
    printf("Going to call query\n");
    printf("Stream2 status %s\n", hipGetErrorName(hipStreamQuery(stream2)));
...... 
```
**output:**
Going to sync stream1
Going to call query
**Stream2 status hipSuccess** <- ideally it should return hipErrorNotReady as stream is busy executing 10second long task
callback_sleep2: Going to sleep for 2sec
callback_sleep2: Exiting now
callback_sleep10: Going to sleep for 10sec
callback_sleep10: Exiting now
Passed
