### ISSUE TITLE
[OpenCL] lack of (async) synchronization exposed by Unit_hipMultiStream_sameDevice and Intel CPU

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#181]
This test exposes another race condition with async commands on Intel OpenCL (see #142). So I don't believe it's an issue in the Intel CPU OpenCL driver. I checked the input pointers and it doesn't wrongly assume aligned input buffers as it vectorizes the inner loop like I initially suspected (it doesn't vectorize across the WG). 

The crash goes away with the additional synchronization added before the free, which indicates the kernel is still running while the free gets hit.  It doesn't go away if I add the extra sync _after_ the free.

```C++
TEST_CASE("Unit_hipMultiStream_sameDevice") {
  constexpr int num_streams{8};
  hipStream_t streams[num_streams];
  float *data[num_streams], *yd, *xd;
  float y{1.0f}, x{1.0f};
  HIP_CHECK(hipMalloc((void**)&yd, sizeof(float)));
  HIP_CHECK(hipMalloc((void**)&xd, sizeof(float)));
  HIP_CHECK(hipMemcpy(yd, &y, sizeof(float), hipMemcpyHostToDevice));
  HIP_CHECK(hipMemcpy(xd, &x, sizeof(float), hipMemcpyHostToDevice));
  for (int i = 0; i < num_streams; i++) {
    HIP_CHECK(hipStreamCreate(&streams[i]));
    HIP_CHECK(hipMalloc(&data[i], NN * sizeof(float)));
    hipLaunchKernelGGL(kernel, dim3(1), dim3(1), 0, streams[i], data[i], xd, NN);
    HIP_CHECK(hipGetLastError());
    hipLaunchKernelGGL(HIP_KERNEL_NAME(nKernel), dim3(1), dim3(1), 0, 0, yd);
    HIP_CHECK(hipGetLastError());
    hipDeviceSynchronize(); // <--- this makes the race go away.
    HIP_CHECK(hipFree(data[i]));
  }
  HIP_CHECK(hipMemcpy(&x, xd, sizeof(float), hipMemcpyDeviceToHost));
  HIP_CHECK(hipMemcpy(&y, yd, sizeof(float), hipMemcpyDeviceToHost));
  REQUIRE(x == Approx(y));
  for (auto& stream : streams) HIP_CHECK(hipStreamDestroy(stream));
}
```

Let me know if there are some fixes I could try @pvelesko, or do you think a review of the OpenCL BE with regards to async command synchronization would be useful? I do not know if this potentially affects LZ too, or is just not exposed by it as it targets GPUs only. It is not exposed when I execute on GPU via the OpenCL BE either, so maybe it the GPU (driver) does less parallel command execution and it is thus not exposed by luck.

**Comment by pvelesko** [comment]
@pjaaskel I don't know what is going on here yet. Last time I was debugging these issues, valgrind was complaining about data races between enqueue barrier and clSVMmemcopy commands which should be ok to be run in parallel from my understanding of the spec?  Furthermore, the number of data races differed by a lot depending on which platform/runtime I was running. It would be helpful if you ran valrgind/helgrind and shared your insights.

**Comment by linehill** [comment]
According to HIP API, hipFree() is supposed to implicitly call the hipDeviceSynchronize().

From HIP API 4.5 - 4.9.2.7 hipFree(): "This API performs an implicit hipDeviceSynchronize() call."

**Comment by pvelesko** [comment]
that was it! good catch @linehill
