### ISSUE TITLE
Unit_hipDeviceSynchronize_Functional depends on timing and fails due to a simple compiler optimization

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#186]
This is one of the failing tests with CPU (#142).

This is a good example of where these tests that depend on timing are unstable and should not be included in a test suite of stable tests in a platform-independent code base (see the discussion in #152). 

Here the test assumes the following kernel takes "long time" so the next copy command should not have started to execute at an assertion point:

```C++
static __global__ void Iter(int* Ad, int num) {
  int tx = threadIdx.x + blockIdx.x * blockDim.x;
  // Kernel loop designed to execute very slowly.
  // so we can test timing-related
  // behavior below
  if (tx == 0) {
    for (int i = 0; i < num; i++) {
      Ad[tx] += 1;
    }
  }
}
```

The delay loop is trivially optimized to a multiplication by _num_ by modern compiler versions. For CPUs this kernel is thus very fast as there are minimal kernel launch overheads, making it fail with CPUs, but pass with GPUs (likely due to the additional overheads involved with the GPU kernel launch). Adding a printf inside the loop or -cl-disable-opts to the clBuildProgram() will make it "slow enough". I'll put the test to the flaky test suite. 

@pvelesko shall we report these issues to HIP upstream somewhere? It likely "works" for AMD GPUs due to the GPU launch overheads even if their compiler would optimize similarly.

**Comment by pvelesko** [comment]
There are specific kernels that are used elsewhere that don't get optimized away. Either way this should get reported so I'll keep this open for now.

**Comment by pvelesko** [comment]
@Sarbojit2019 Change this test as part of #238
