### ISSUE TITLE
Can we have device side clock() or clock64() implementation?

### ISSUE THREAD

**Issue by Sarbojit2019** [CHIP-SPV/chip-spv#189]
It will be good to have device side implementation of clock or clock64, currently it is marked as always return 0. if it can't be done at the moment then at last we should generate compile time warning saying it is not implemented. Analyzing kernel issues will be more challenging hence up ahead warning to the user will be definitely a time saver. 
I wrote sample kernel (mentioned below) which hangs the GPU, after quite a bit of analysis I realized the clock64 is always returning zero hence kernel is running infinite.

```
__global__ void wait_until( size_t timeout) {
   uint64_t start = clock64();
   uint64_t end = start;
   while(abs(end-start) < timeout) {
      // do something here
      end = clock64();
   }
} 
```

**Comment by franz** [comment]
I have actually tried to implement it for Intel GPU with intrinsics from that link, but it didn't work. Can't remember if it was a problem with the translator or something else.

**Comment by Sarbojit2019** [comment]
I have raise a PR#238, please take a look.
