### ISSUE TITLE
Combining the use of hipcc as the compiler and linking against hip::host or hip::device leads to build errors

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#193]
This results in us using hipcc as the compiler and adding all the HIP compile options on top of that

```
clang-15: error: only one offload target is supported
```

**Comment by pvelesko** [comment]
not sure where the compiler gets set to hipcc. @linehill Any ideas?

**Comment by pvelesko** [comment]
User error: overriding things in CMakeLists.txt

**Comment by pvelesko** [comment]
CMakeLists.txt 


```
project(simple)

cmake_minimum_required(VERSION 3.10)

# Search for rocm in common locations
list(APPEND CMAKE_PREFIX_PATH $ENV{HIP_PATH})

# Find hip
find_package(hip)

# Set compiler and linker
set(CMAKE_CXX_COMPILER ${HIP_HIPCC_EXECUTABLE})
set(CMAKE_CXX_LINKER   ${HIP_HIPCC_EXECUTABLE})
set(CMAKE_BUILD_TYPE Release)

# Create the excutable
add_executable(saxpy_hip saxpy_hip.cpp)

# Link with HIP
target_link_libraries(saxpy_hip hip::host)
```

**Comment by pvelesko** [comment]
I suppose we should have a check for this

**Comment by linehill** [comment]
> `clang-15: error: only one offload target is supported`

I'm guessing that the `--offload` option is given twice to the Clang which does give an error if it receives multiple occurrences of it (even tough the option value is same).

> `set(CMAKE_CXX_COMPILER ${HIP_HIPCC_EXECUTABLE})`

This probably introduces the duplicate option. CMake constructs compile command for the `hipcc` with options including the `--offload `and `hipcc` inserts another `--offload` option for the clang invocation.

**Comment by pvelesko** [comment]
That was the root cause of the issue (user error) that's why I posted it here. 
The question remains:

> Should we have a check for this? Even though doing this is not described in using HIP with Cmake

**Comment by pvelesko** [comment]
The sample came from HIP cookbook so we will need to support this.

**Comment by pjaaskel** [comment]
Is this a problem with our hip_config where we should not print _--offload=spirv64_ for _--cpp_config_? Then it gets propagated to makefiles and we get the double --offload option issue. I see the same problem when building hipCUB. Does AMD HIP print it?

**Comment by pjaaskel** [comment]
Yeah, that seems to be the problem, if I understand hipconfig.pl right. Trying to a fix...

**Comment by pjaaskel** [comment]
OK, Henry told that we need to include the offload switch since the second supported way to compile is to call clang++ directly and then this offload arg is of course needed to be included. Will kludge this for now to fix compatibility with hip library build files.

**Comment by pvelesko** [comment]
> understand hipconfig.pl right
we don't use that anymore it's been replaced by HIPCC

**Comment by pjaaskel** [comment]
OK, anyhow the fix is in the above HIPCC PR.

**Comment by pjaaskel** [comment]
Yep, here ^
