### ISSUE TITLE
Wrongly passes the CHIP-SPV CXX build flags down to the device bitcode compilation flags

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#2]
Currently the CMAKE_CXX_FLAGS are used for the device compilation too. Unfortunately, the default is -O0 which marks the device functions 'optnone' and the _required_ transformation passes of HIP are not ran to those functions (including the actual kernel function). Incidentally this means that with the default optimization flags the device build is broken (works for the kernels where the passes are not necessary) and the user should pass CMAKE_CXX_FLAGS=-O2 for the intended functionality.

This should be fixed such that we ensure the device binaries are compiled with flags that do not prevent _required_ passes to be ran.

**Comment by pjaaskel** [comment]
Thanks Henry! The symptom was fixed well and correctly, but I think passing the host runtime build flags down to device compilation is simply wrong. In OpenCL they pass it with clBuildProgram(). If there is no such feature in CUDA/HIP, it'd be better a separate build setting (for the default) and perhaps an env for the runtime.

**Comment by pvelesko** [comment]
Sorry for the delay in this - I took a bit of time off.

> passing the host runtime build flags down to device compilation is simply wrong
When you say device compilation, are you talking about backend JIT options for "device compilation" of kernels? 
Or are you talking about passing `CMAKE_CXX_FLAGS` to `devicelib_bc` target?

**Comment by pjaaskel** [comment]
The JIT compilation mostly, which hopefully includes optimization of the linked in parts of the devicelib too. But this is not a critical issue after the Henry's fix.

**Comment by pvelesko** [comment]
@pjaaskel The JIT compilation options are currently hard-coded with options taken from HIPCL and HIPLZ, respectively. Are you saying that there should be a new CMake option or an env variable that would be passed down to the JIT compiler?

**Comment by pjaaskel** [comment]
I think so, yes.

**Comment by pvelesko** [comment]
@pjaaskel PR: #7
