### ISSUE TITLE
[Level Zero] Unexpected sync between unrelated command queues

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#207]
`TestStreamSemantics_2` 

1. submit work to a non-blocking queue
2. submit a memcopy to the default queue
3. memcopy executes a `CHIPQueue::finish()`
4. the finish() will not return until the callback is completed

**Comment by Sarbojit2019** [comment]
Update : At this moment it is not proved to be Level-zero issue. We found some missing changes in CHIP_SPV runtime, @pvelesko is working on it.
