### ISSUE TITLE
HIP_VERSION_MAJOR, HIP_VERSION_MINOR nor HIP_VERSION are defined at build time

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#225]
These flags don't seem to appear when building HIP files. They can be used to check for features, so we should define them somewhere.

**Comment by pvelesko** [comment]
`CMakeLists.txt:480`

```
set(HIP_VERSION_MAJOR 5)
set(HIP_VERSION_MINOR 1)
set(HIP_VERSION_PATCH 0)
```

@pjaaskel is this not working?

**Comment by linehill** [comment]
It's a local script of mine that runs ROCm's and CHIP-SPV's hipcc with same command line flags.

**Comment by pjaaskel** [comment]
Sounds useful enough script to share, can you put it to the repo under devel-tools/ or such directory?
