### ISSUE TITLE
Implement warpSize

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#226]
Warp vs. subgroup is a messy affair (#219), so I suggest we define warpSize to 32 at least when building CUDA sources and pass the required subgroup annotation whenever a kernel refers to warpSize or any of the shuffles that rely on a fixed warp size (or thread-to-lane mapping). 

* CUDA defines the [warp size as a device-wide constant (32)](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#simt-architecture). 

* [HIP defines](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_kernel_language.md#warpsize): "Note that all current Nvidia devices return 32 for this variable, and all current AMD devices return 64. Device code should use the warpSize built-in to develop portable wave-aware code." which sounds like it could be a per-kernel value, but since it's also [in the device properties](https://rocm-developer-tools.github.io/HIP/structhipDeviceProp__t.html#af3357d33c004608bf05bc21a352be81b), it has to be device specific.

This means that we might do with a simple `constexpr const unsigned int warpSize = 32` global variable implementation.
I believe most of the workloads originate from CUDA so it might be more robust to use and optimize for 32 here instead of 64? But let's make it a single global so it's easy to tweak/tune in the future. However, we have to fix it to something otherwise SPIR-Vs which rely on warpSize become non-portable (unless we introduce the warpSize as a SPIR-V built-in).

The warpSize parameter of the [HIP-versions of the shuffles](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_kernel_language.md#warp-shuffle-functions) has to then check if the warpsize of the device matches the given one, if not, adjust the lane mapping function accordingly.

**Comment by pjaaskel** [comment]
@Kerilk @franz @pvelesko @linehill I plan to implement warpSize since rocPRIM uses it. Please check my above rationale and see if I missed something or not.

**Comment by Kerilk** [comment]
We can start with this. In the long run we may need to be more flexible, for performance reasons. 32 may not be an optimal subgroup size.

**Comment by pjaaskel** [comment]
> for performance reasons. 32 may not be an optimal subgroup size.

I agree. This is heavily HW dependent (like seen with AMD 64 vs NVIDIA 32), but making it more flexible while being portable requires the SPIR-V builtin, I believe.

**Comment by pjaaskel** [comment]
...actually it could be a good use case for SPIR-V specialization constants.
