### ISSUE TITLE
Unit_hipMemsetAsync_QueueJobsMultithreaded causes a node crash 

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#241]
Tested on Gen9 and ATS. Must be run for a while. This might have something to do with deadlock detection on JLSE.

**Comment by pvelesko** [comment]
@Sarbojit2019 Can you please run this test on Intel systems for a while to confirm that it works for you?

**Comment by Sarbojit2019** [comment]
@pvelesko, I have tested this with latest chip-spv::main (branch) on ATS. I could successfully run 500 iteration for Level0 and Opencl.

**Comment by Sarbojit2019** [comment]
I am closing the ticket as I am not able to reproduce the issue with latest. Feel free to reopen in case required.
