### ISSUE TITLE
HIP-SYCL Interop - unable to destroy CHIPContextLevel0

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#253]
For all 4 of these samples, if we try to destroy the context we get a segfault. I can see how that could happen when we are initializing CHIP-SPV from SYCL handles since we do not own the memory for the provided context but the other way around doesn't make sense to me since the default is for MKL to not retain the context.

**Comment by Sarbojit2019** [comment]
Fix raised in PR #260

**Comment by Sarbojit2019** [comment]
Fixed
