### ISSUE TITLE
Macro to detect that we are targeting chip-spv when building with hipcc or clang

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#257]
This would be very useful when porting libs. E.g. `__chipspv__` or such could be then used to add alternative codes for CHIP-SPV. I suppose we do not have any we can use at the moment?

**Comment by pvelesko** [comment]
__HIP_PLATFORM_SPIRV__ ?

**Comment by pjaaskel** [comment]
Right. But we must then assume it's given via -D if compiling directly using clang as it's not implicitly defined by clang. Not sure if we need to though...

**Comment by pvelesko** [comment]
Not sure I understand. What is the issue if it is passed in via -D?

**Comment by pjaaskel** [comment]
Might not be an issue if we always assume all hipcc-config flags must be passed to clang when targeting hip/chip-spv.

**Comment by pvelesko** [comment]
-D__HIP_PLATFORM_SPIRV__ is passed in always when targeting chip-spv

**Comment by pjaaskel** [comment]
Yes, by hipcc, I was thinking when the user calls clang directly, but we can assume (s)he then must pass all the hipcc-config flags.

**Comment by pvelesko** [comment]
Yeah, passing `__HIP_PLATFORM_SPIRV__` is critical
