### ISSUE TITLE
Level Zero driver crash while performing 3D mem copy

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#262]
Level Zero crashes when performing a `width{10}, height{10}, depth{10}` memcopy. The copy is performed by looping over the dimensions and doing regular memcopies (as opposed to doing a Level Zero region memcopy). The same scenario works for OpenCL. 

The Issue also goes away if I reduce the the copy to 2D `width{10}, height{10}, depth{1}`
[passing.txt](https://github.com/CHIP-SPV/chip-spv/files/10075211/passing.txt)
[failing.txt](https://github.com/CHIP-SPV/chip-spv/files/10075212/failing.txt)

**Comment by Sarbojit2019** [comment]
@pvelesko, could you please share more details about the test?
I modified "chip-spv/samples/10_memcpy3D" as per your comment but did not see any crash.

**Comment by pvelesko** [comment]
Graphs branch @Sarbojit2019

**Comment by Sarbojit2019** [comment]
Fix is merged hence closing the ticket.
