### ISSUE TITLE
hipcc - prevent HIP options from being passed in twice

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#271]
If the build system uses `hipconfig -C` to manually specify the offload flags we should parse such case otherwise clang will complain about multiple offload architectures being requested.

**Comment by pjaaskel** [comment]
I recall adding something related to this already? Maybe that's not pulled in?

**Comment by pjaaskel** [comment]
https://github.com/CHIP-SPV/HIPCC/pull/2
