### ISSUE TITLE
Need C compatible header for hip_to_chip.hh

### ISSUE THREAD

**Issue by Sarbojit2019** [CHIP-SPV/chip-spv#277]
hipBlas supports C application but CHIP-SPV's hip_to_chip.hh is not C compatible hence compilation error.
I think we can do something similar to what is done in HIP runtime.

**Comment by pvelesko** [comment]
Duplicate of 272?

**Comment by Sarbojit2019** [comment]
Possible if #272 covers hip_to_chip.hh file change as well. But yeah over all idea is same CHIP-SPV is not friendly with C.

**Comment by Sarbojit2019** [comment]
I have verified with latest CHIP-SPV and it is still not working with C source, hence I am reopening it.
@pvelesko, can you point to the fix which should resolve build error?

**Comment by pvelesko** [comment]
I closed it since it was a duplicate issue. I don't have the fix yet.

**Comment by Sarbojit2019** [comment]
OK, There was nothing mentioned on why it is closed hence got confused.
Let call it out, this task is getting tracked in #272 hence no action is needed but I would prefer to keep it open until it is fixed.

**Comment by pvelesko** [comment]
I mentioned it in the previous comment that #272 is tracking this issue but if you want a separate ticket then that's fine we can keep this open.
