### ISSUE TITLE
error: invalid argument '-std=c99' not allowed with 'HIP'

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#298]
This is coming from libCEED. I can remove this option and make some minor changes to the code to get it to compile but this is still an issue. 

Does adding `-x hip` enforce C++ underneath? @pjaaskel @linehill

**Comment by pvelesko** [comment]
So basically the file in question doesn't have any HIP and they add CPP flags to when compiling all C code. 

```
%.c.tidy : %.c
	$(CLANG_TIDY) $(TIDY_OPTS) $^ -- $(CPPFLAGS) --std=c99 -I$(CUDA_DIR)/include -I$(HIP_DIR)/include -DCEED_JIT_SOUCE_ROOT_DEFAULT="\"$(abspath ./include)/\""
```

Is it fair to say that their build system is wrong and no change necessary on our end?

**Comment by linehill** [comment]
`-x <mode>` option tells compiler to ignore source suffixes and treat the inputs in `<mode>` language. As HIP language features are extension of C++ and hence `-x hip` implies C++.

> ... Is it fair to say that their build system is wrong and no change necessary on our end?

The CPPFLAGS is a variable for C preprocessor (step), so it is not meant to have C++ compilation flags.
