### ISSUE TITLE
License texts missing

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#3]
I think most of the source files miss the license blurbs.

**Comment by linehill** [comment]
Have we decided what license the CHIP-SPV should use?

**Comment by pvelesko** [comment]
@Kerilk

**Comment by franz** [comment]
Pekka suggested MIT, also AMD's HIP is MIT so it makes sense, plus MIT should be compatible with all included projects (but i'm no legal expert). Other licenses could work too, but GPL and similar are likely not possible.

**Comment by franz** [comment]
fixed by PR #113
