### ISSUE TITLE
Printf argument counting issue?

### ISSUE THREAD

**Issue by Kerilk** [CHIP-SPV/chip-spv#30]
This seems a bit too simple to work, just raising the issue here before I forget:
https://github.com/CHIP-SPV/chip-spv/blob/6487cbf143004a6f9abaa3af85dd8910040cda66/llvm_passes/HipPrintf.cpp#L65-L67

Correct me if I am wrong but wouldn't this give different or wrong results for `"%%%"` and `"%% %"`?
`"%%%"` should give 2 or 1 depending if count is implemented with a greedy regexp or not respectively and `"%% %"` should yield 2 irrespective of count implementation, which would be wrong.

**Comment by pjaaskel** [comment]
Yep, I noticed that thinko a while ago and attempted to fix it in my branch, but it's likely still too simple: https://github.com/parmance/chip-spv/blob/printf/llvm_passes/HipPrintf.cpp#L77 -- need to think and poke about it a bit more.

The main branch has quite an old version of the printf implementation. I'm trying to merge in the printf branch, but I'm currently having troubles getting the main branch to build and work so I could compare the test status.

**Comment by pvelesko** [comment]
Is this still active?
