### ISSUE TITLE
Running Level Zero unit tests in parallel via ctest causes bus error

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#316]
OpenCL can run be run reliably on 16 threads, Level Zero ends up failing.

**Comment by pvelesko** [comment]
Simply compiling and performing the test discovery is enough to crash the GPU:
* Compilation affects the GPU because the test discovery happens post-build which invokes the driver. 
* By default, Level Zero is used. 
* Level Zero has proved to be quite unstable especially when multiple threads are used.
* Multiple threads are always used when building so `zeInit` is called from multiple threads.
@Sarbojit2019

**Comment by pjaaskel** [comment]
Shall we (again) switch back to OpenCL by default?

**Comment by pvelesko** [comment]
I don't see any reason to do that at this time. Level Zero works better overall anyways and the user is free to chose the backend.
