### ISSUE TITLE
Support for hipComplex

### ISSUE THREAD

**Issue by elwasif** [CHIP-SPV/chip-spv#343]
Hello,
    Implementation for the hipComplex type appears to be missing from the current implementation. The file https://github.com/CHIP-SPV/chip-spv/blob/main/include/hip/spirv_hip_complex.h does not have an implementation. This is needed to implement   the hipfft  library interface (the hipfft API uses hipfftComplex which is the same type).

**Comment by pvelesko** [comment]
@elwasif I copied over the implementation from hipamd https://github.com/CHIP-SPV/chip-spv/pull/358 please let me know if it works for you.

**Comment by pvelesko** [comment]
@elwasif I added a simple sample that compiles and runs now. Also, if you have a sample file I can include in our tests that would be good too.

**Comment by pvelesko** [comment]
@elwasif

**Comment by elwasif** [comment]
@pvelesko  This works for me now, Ok to close.
