### ISSUE TITLE
fp16 related build issues on JLSE

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#352]
```
[100%] Built target RecursiveGaussian
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fp16_math.dir/half_math.cpp.o: in function `__half::operator float<float, (void*)0>() const':
/home/pvelesko/t/chip-spv/include/hip/spirv_hip_fp16.h:296: undefined reference to `__extendhfsf2'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fp16_math.dir/half_math.cpp.o: in function `__half<float, nullptr>':
/home/pvelesko/t/chip-spv/include/hip/spirv_hip_fp16.h:167: undefined reference to `__truncsfhf2'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fp16_math.dir/half_math.cpp.o: in function `__half<short, nullptr>':
/home/pvelesko/t/chip-spv/include/hip/spirv_hip_fp16.h:181: undefined reference to `__truncsfhf2'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fp16_math.dir/half_math.cpp.o: in function `__half::operator unsigned short<unsigned short, (void*)0>() const':
/home/pvelesko/t/chip-spv/include/hip/spirv_hip_fp16.h:310: undefined reference to `__extendhfsf2'
```

**Comment by pjaaskel** [comment]
This is likely due to a too old compiler runtime which doesn't implement those builtins. Can you use compiler-rt from LLVM or a newer libgcc here?

**Comment by pvelesko** [comment]
I use clang15 from a while ago. If something newer is required we should update the docs. 

If I compile clang 16 that should fix this? @pjaaskel

**Comment by pjaaskel** [comment]
This is because of the compiler runtime lib, not the directly compiler itself. I think your options here are a) upgrade libgcc (since Clang uses that by default, I think) or b) use LLVM project's compiler-rt (I do not know how well it works as a libgcc replacement nowadays, it's been a long time since I tested it). 

Yep, we should document the minimal version of libgcc/libcompiler-rt required (I do not know it yet).

**Comment by pvelesko** [comment]
> a) upgrade libgcc (since Clang uses that by default, I think)

Is this something I can do easily on a shared system? If I recall correctly libgcc upgrading is tricky. 

> b) use LLVM project's compiler-rt (I do not know how well it works as a libgcc replacement nowadays, it's been a long time since I tested it)

I'll try it this. 


> Yep, we should document the minimal version of libgcc/libcompiler-rt required (I do not know it yet).

Wouldn't it be the same as hipamd?

**Comment by franz** [comment]
I've run into the same problem (though it was complaining about `__gnu_f2h_ieee`) on my workstation, with Clang 14 (but 15 works for some reason). A simple workaround that solved it for me (and should work on all reasonably recent CPUs) was to add `-march=native` to chip-spv's cmake cxx flags. Alternatively using just `-mf16c` should work, but i haven't tried.
