### ISSUE TITLE
Issue with linking device code

### ISSUE THREAD

**Issue by colleeneb** [CHIP-SPV/chip-spv#368]
It looks like linking device code does not work.

It also looks like this is known--the sample hipDeviceLink was disabled (https://github.com/CHIP-SPV/chip-spv/blob/d2874f1a90a772d05cf1186e36ff2e3e2c30c359/samples/CMakeLists.txt#L132).

We need this for GAMESS to work with CHIP-SPV, though. I put a GAMESS-relevant reproducer here: https://github.com/colleeneb/device_linking_hip (however, I think it's probably the same as in hipDeviceLink.). 

Is it possible to patch CHIP-SPV so that this will work?

Thanks!

**Comment by pjaaskel** [comment]
Didn't you fix this @linehill ?
