### ISSUE TITLE
[libCEED] Error in uninit

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#373]
```
// Uninitializes the backend when the application exits.
void __attribute__((destructor)) uninitializeBackend() {
  // Generally, __hipUnregisterFatBinary would uninitialize the
  // backend when it finishes unregistration of all modules. However,
  // there won't be hip(Un)registerFatBinary() calls if the HIP
  // program does not have embedded kernels. This makes sure we
  // uninitialize the backend at exit.
  if (Backend && getSPVRegister().getNumSources() == 0) {
    CHIPUninitialize();
    delete Backend;
    Backend = nullptr;
  }
}
```

When this function is called, `getNumSources()` returns 1 which prevents the backend from properly uninitializing resulting in segfaults.

**Comment by linehill** [comment]
There are two path to the CHIP-SPV uninitialization:

* via `__hipUnregisterFatBinary()` when registered module count reaches zero or
* via `uninitializeBackend()` for covering uninitialization in cases where HIP applications do not have embedded modules (in which case the `__hipUnregisterFatBinary()` won’t be called at all).

The order of the `__hipUnregisterFatBinary()` and `uninitializeBackend()` calls are undefined which could explain the case you see in the `uninitializeBackend()`.

Does this issue arise in a hipRTC application? `hipModuleLoadData()` calls do increase the count returned by the `getNumSources()`.  Perhaps, the client did not call `hipModuleUnload()` on a module before the program exit?

**Comment by pvelesko** [comment]
> Does this issue arise in a hipRTC application? 

yes

> Perhaps, the client did not call hipModuleUnload() on a module before the program exit?

very likely but it's also very common for things to not get cleaned up as they're supposed to. Like creating streams and exiting without destroying.
