### ISSUE TITLE
[Kokkos] hipcc doesn't export __HIPCC__

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#388]

**Comment by linehill** [comment]
I'm seeing the hipcc exporting the macro:

```
$ cat hipcc-macro.cpp 
#include <hip/hip_runtime.h>
#ifndef __HIPCC__
#error __HIPCC__ was not defined
#endif
$ ../install/bin/hipcc hipcc-macro.cpp -c
Hip Clang Compiler not found

$  echo $?
0
```
On the other hand, if the source is compiled in C++ mode then the macro is not defined:

```
$ ../install/bin/hipcc -x c++ hipcc-macro.cpp -c
Hip Clang Compiler not found
clang-15: warning: argument unused during compilation: '--offload=spirv64' [-Wunused-command-line-argument]
clang-15: warning: argument unused during compilation: '-nohipwrapperinc' [-Wunused-command-line-argument]
hipcc-macro.cpp:3:2: error: __HIPCC__ was not defined
#error __HIPCC__ was not defined
 ^
1 error generated.
```
Which seems intended as [clang](https://github.com/llvm/llvm-project/blob/f9f4767af9f3d89792d67ae8c5f65913ff263b89/clang/lib/Frontend/InitPreprocessor.cpp#L578) only defines the `__HIPCC__` macro only in HIP language mode.

**Comment by pvelesko** [comment]
For some reason it's not defined when compiling Kokkos::HIP. I'll try to make a reproducer.
