### ISSUE TITLE
hipcc fail on -V

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#390]
```
hipcc -V ./deviceMalloc.cpp
clang-15: error: unsupported option '-V ./deviceMalloc.cpp'
clang-15: error: no input files
```

**Comment by linehill** [comment]
hipamd's hipcc doesn't support the option either and also it is not it is not recognized by gcc and g++. What is this option? All I know about the option from [here](https://github.com/llvm/llvm-project/blob/1e4325f30c2494637626a978c54b41c8ca7ec0ff/clang/include/clang/Driver/Options.td#L818) is that the option takes a value which is the reason the hipcc gives the "no input files" error.
