### ISSUE TITLE
[hipcc] mixing compilation and linking in a single step is not currently supported

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#411]
you can compile source to objects and then link but this will fail currently:

```
hipcc obj.o src.cc -o program
```

this is due to needing the `-x hip` option when compiling but having this option when linking will cause errors. Not sure if there's a simple workaround or if we have to separate these stages in hipcc.

**Comment by linehill** [comment]
The `-x <lang>` option applies to files appearing after it. There is also a way to clear the effects of the flag with `-x none` so the issue can be worked around with:
```bash
hipcc -x none obj.o -x hip src.cc -o program
```
