### ISSUE TITLE
Missing `__ldg` routines

### ISSUE THREAD

**Issue by rgayatri23** [CHIP-SPV/chip-spv#471]
I noticed that the `__ldg` routines are missing which are a part of the `hip_ldg.h` file.
https://rocm-developer-tools.github.io/HIP/hip__ldg_8h_source.html

Is there any update on support for these routines on level-zero?

**Comment by linehill** [comment]
We do have dummy implementations for the routines in include/hip/spirv_hip_ldg.h but it's not connected to the base HIP headers - probably, they were but we has lost it at some point.
