### ISSUE TITLE
OpenCL Regressions When Using Clang14

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#48]
A lot tests result in failures due to `CL_INVALID_KERNEL_ARGS` when using clang14 + OpenCL. This is not the case for Clang13 

```bash
CHIPKernelOpenCL::CHIPKernelOpenCL(const cl::Kernel &&, std::string, OCLFuncInfo *): Assertion `FuncInfo_->ArgTypeInfo.size() == NumArgs' failed.
```

**Comment by pvelesko** [comment]
For some reason this does not affect Iris

**Comment by linehill** [comment]
OpenCL test cases fail on some Intel Compute Runtime versions. The issue you described is probably related to this intel/compute-runtime#535.

For me, the OpenCL test cases pass on version 22.04.22286.

**Comment by zjin-lcf** [comment]
Running a sample (e.g. matrix_multiply) shows the error with BE=opencl on Intel DevCloud.  Could you please update the document (install) so that the BE=level0 by default ?
