### ISSUE TITLE
CP2K is crashing with OOM error

### ISSUE THREAD

**Issue by Sarbojit2019** [CHIP-SPV/chip-spv#487]
Even with PR[#449](https://github.com/CHIP-SPV/chip-spv/pull/449) I could see CP2K is throwing OOM error. 
![image](https://github.com/CHIP-SPV/chip-spv/assets/52556743/f5a0412c-03b8-46a3-9019-691a968c5d10)

Steps to reproduce the issue:

1. Get CP2K source from https://github.com/rgayatri23/cp2k
2. cd cp2k/src/dbm; make
3. run ./dbm_miniapp.x

**Comment by pjaaskel** [comment]
Does it reproduce also with the OpenCL BE?

**Comment by Sarbojit2019** [comment]
It must be some setup mess-up I tried multiple clean systems and I am not able to reproduce the issue with lates main. I am closing the ticket as of now.
