### ISSUE TITLE
SPIR-V Parser lacking support for structures, and Constant-Creation Instructions 

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#52]
Currently any Kokkos::HIP application segfaults during processing of a SPIR-V Structure.

````
    if (Opcode_ == spv::Op::OpTypeStruct) {
      size_t TotalSize = 0;
      for (size_t i = 2; i < WordCount_; ++i) {
        int32_t MemberId = OrigStream_[i];
        TotalSize += TypeMap[MemberId]->size();
      }
      return new SPIRVtypePOD(Word1_, TotalSize);
    }
````

Furthermore `TypeMap` does not contain all the POD sizes which causes a segfault.

**Comment by pjaaskel** [comment]
This was likely fixed by #313, can you confirm?

**Comment by pvelesko** [comment]
fixed.

**Comment by pvelesko** [comment]
Can't confirm yet as I ran into new issues while trying to build Kokkos.

**Comment by pjaaskel** [comment]
Is it still appearing?
