### ISSUE TITLE
Device variable synchronization

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#57]
Device variable initialization calls 

```
  if (QueuedKernels)
    Queue->finish();
```

which results kernel launches being a blocking operation which violates HIP queue semantics.

**Comment by linehill** [comment]
Could you elaborate what rule/behavior is being violated in detail? Much appreciated if you could send a reproducer to demonstrate the issue.

**Comment by pvelesko** [comment]
@linehill The kernel submit command should not block on the host. By calling `Queue->finish()` you end up doing exactly that. Instead, barriers should be used instead

**Comment by linehill** [comment]
Sure, the blocking is not the best possible design choice here. However, it does not have a significant impact as the device variable preparation process occurs once per device for its lifetime. Only the first kernel launch gets blocked at most (per device) and subsequent kernel launches are carried out without blocking.
