### ISSUE TITLE
Failing printf & abort

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#64]
Some of the currently failing samples:
```
         96 - abort (Failed)
        135 - PrintfSimple (Failed)
        136 - PrintfNOP (Failed)
        137 - PrintfDynamic (Failed)
```

**Comment by linehill** [comment]
Bisected the revisions to find the source of the issue. The earliest printf failures were introduced in the commit `86f9ae8f7ae64f624862e166412e76823391abfa` (Create a new command list every time - stream pass).

**Comment by linehill** [comment]
The printf issues might be caused by the lack of zeFenceHostSynchronize() or zeCommandQueueSynchronize() calls at the appropriate points which ensures the printf buffers get flushed. https://spec.oneapi.io/level-zero/latest/core/PROG.html?highlight=printf#formatted-output.

**Comment by linehill** [comment]
Made a fix candidate.
