### ISSUE TITLE
[SYCL-HIP interop | Level Zero] get_native() handle for queue returns nullptr

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#66]
```
myQueue.template get_native<sycl::backend::level_zero>(); // returns nullptr.
````

**Comment by Sarbojit2019** [comment]
@pvelesko, Sycl defers lz queue creation until any work gets submitted to the device hence "**get_native<sycl::backend::level_zero>();**" is returning nullptr in **samples/sycl_hip_interop**. I modified the sample to add dummy task before query Native handle, what that I could see non-zero queue handle for **"get_native<sycl::backend::level_zero>();"**. Please take a look at the attached modified sample.

However this fix exposed a bug in the CHIP-SPV runtime teardown case for which I have raised a fix in PR#280
[sycl_chip_interop.cpp.txt](https://github.com/CHIP-SPV/chip-spv/files/10206785/sycl_chip_interop.cpp.txt)

**Comment by Sarbojit2019** [comment]
Closing it as "not a bug" feel free to re-open in case you feel it is otherwise.

**Comment by pvelesko** [comment]
@Sarbojit2019 Queue handle is not being used. 

```
void CHIPBackendLevel0::initializeFromNative(const uintptr_t *NativeHandles,
                                             int NumHandles) {
  logTrace("CHIPBackendLevel0 InitializeNative");
  MinQueuePriority_ = ZE_COMMAND_QUEUE_PRIORITY_PRIORITY_HIGH;

  ze_driver_handle_t Drv = (ze_driver_handle_t)NativeHandles[0];
  ze_device_handle_t Dev = (ze_device_handle_t)NativeHandles[1];
  ze_context_handle_t Ctx = (ze_context_handle_t)NativeHandles[2];

  CHIPContextLevel0 *ChipCtx = new CHIPContextLevel0(Drv, Ctx);
  ChipCtx->setZeContextOwnership(false);
  addContext(ChipCtx);

  CHIPDeviceLevel0 *ChipDev = CHIPDeviceLevel0::create(Dev, ChipCtx, 0);
  ChipCtx->setDevice(ChipDev);

  LOCK(Backend->BackendMtx); // CHIPBackendLevel0::StaleEventMonitor
  ChipDev->LegacyDefaultQueue = ChipDev->createQueue(NativeHandles, NumHandles);

  StaleEventMonitor_ =
      (CHIPStaleEventMonitorLevel0 *)Backend->createStaleEventMonitor_();
  CallbackEventMonitor_ =
      (CHIPCallbackEventMonitorLevel0 *)Backend->createCallbackEventMonitor_();
  setActiveDevice(ChipDev);
}
```

**Comment by Sarbojit2019** [comment]
@pvelesko 
CHIP-SPV does use native queue handle passed, check the below code.
`
CHIPQueue *CHIPDeviceLevel0::createQueue(const uintptr_t *NativeHandles,
                                         int NumHandles) {
  ze_command_queue_handle_t CmdQ = (ze_command_queue_handle_t)NativeHandles[3];
  CHIPQueueLevel0 *NewQ;
  if (!CmdQ) {
    logWarn("initializeFromNative: native queue pointer is null. Creating a "
            "new queue");
    NewQ = new CHIPQueueLevel0(this, 0, 0);
  } else {
    NewQ = new CHIPQueueLevel0(this, CmdQ);
    // In this case CHIP does not own the queue hence setting right ownership
    if (NewQ != nullptr) {
      NewQ->setCmdQueueOwnership(false);
    }
  }

  return NewQ;
}
`

**Comment by pvelesko** [comment]
oh my bad
