### ISSUE TITLE
CHIPBackend::uninitialize()

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#71]
> WRT StaleEventMonitor, IMO there is a bigger issue: calling CHIPUninitialize from __hipUnregisterFatBinary. That handler itself is called from shared library destructors, which are called after main() function returns, and these are called in reverse order of their constructors (so some of the shared libraries might be already unloaded). Doing this kind of uninitialization after main() is unsafe, because the program is no longer in a normal state. There are two solutions: 1) make a new hip API (hipUninit or such) that the application can to explicitly call, or 2) do nothing, and let the kernel clean up everything. 1) is useful for debugging memory leaks, otherwise the default should be 2).

@franz can you elaborate on what shared libraries might be already unloaded and how that could cause issues?

Overall, I agree that that this function is not necessary - I implemented it to make sure that we don't have events remaining that haven't been garbage collected.

**Comment by franz** [comment]
My mistake, i have checked with LD_DEBUG and the shared library destructors are called in correct order. I was referring to the Intel driver libraries loaded by libOpenCL / libze loaders.
