### ISSUE TITLE
[SYCL-HIP interop] segfault when compiled in `Release` configuration

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#73]
This assert doesn't fire:

```
  assert(ChipDev->AllocationTracker && "AllocationTracker was not created!");
  if (!ChipDev->AllocationTracker->reserveMem(Size))
    return nullptr;
```

**Comment by pvelesko** [comment]
Can you reproduce?  @franz

**Comment by linehill** [comment]
It’s intended behavior by CMake (and probably in general) that the assert does not fire in release mode.

The assert() is usually/mainly intended only for debugging and development and dropped out in the release versions for performance. In the release mode the CMake compiles the code with `-DNDEBUG` which removes assert calls.

**Comment by pvelesko** [comment]
Ah didn't know that about asserts and debug. Explains why the assert doesn't fire but the bug remains. Were you able to reproduce? @linehill

**Comment by linehill** [comment]
I haven't been able to reproduce the issue. @franz said he takes a look at it.

**Comment by franz** [comment]
@pvelesko  yeah i can reproduce, and i already see the problem (missing populateDeviceProperties)
