### ISSUE TITLE
Failed to clone 'HIP'

### ISSUE THREAD

**Issue by zjin-lcf** [CHIP-SPV/chip-spv#84]
~/chip-spv$ git submodule update --init --recursive
Submodule 'HIP' (git@github.com:CHIP-SPV/HIP.git) registered for path 'HIP'
Submodule 'bitcode/ROCm-Device-Libs' (https://github.com/RadeonOpenCompute/ROCm-Device-Libs.git) registered for path 'bitcode/ROCm-Device-Libs'
Submodule 'hip-testsuite' (https://github.com/CHIP-SPV/hip-testsuite.git) registered for path 'hip-testsuite'
Cloning into '/path/to/chip-spv/HIP'...
fatal: Could not read from remote repository.

**Comment by pvelesko** [comment]
Hmm strange. Where does "/path/to/chip-spv/HIP" come from I wonder?

```
pvelesko@jlselogin4:/tmp> git clone https://github.com/CHIP-SPV/chip-spv.git --recursive
Cloning into 'chip-spv'...
remote: Enumerating objects: 12384, done.
remote: Counting objects: 100% (3225/3225), done.
remote: Compressing objects: 100% (1149/1149), done.
remote: Total 12384 (delta 2208), reused 2743 (delta 2058), pack-reused 9159
Receiving objects: 100% (12384/12384), 9.70 MiB | 17.42 MiB/s, done.
Resolving deltas: 100% (8464/8464), done.
Submodule 'HIP' (git@github.com:CHIP-SPV/HIP.git) registered for path 'HIP'
Submodule 'bitcode/ROCm-Device-Libs' (https://github.com/RadeonOpenCompute/ROCm-Device-Libs.git) registered for path 'bitcode/ROCm-Device-Libs'
Submodule 'hip-testsuite' (https://github.com/CHIP-SPV/hip-testsuite.git) registered for path 'hip-testsuite'
Cloning into '/tmp/chip-spv/HIP'...
remote: Enumerating objects: 45889, done.
remote: Counting objects: 100% (633/633), done.
remote: Compressing objects: 100% (482/482), done.
remote: Total 45889 (delta 197), reused 566 (delta 149), pack-reused 45256
Receiving objects: 100% (45889/45889), 17.53 MiB | 21.45 MiB/s, done.
Resolving deltas: 100% (32010/32010), done.
Cloning into '/tmp/chip-spv/bitcode/ROCm-Device-Libs'...
remote: Enumerating objects: 7855, done.
remote: Counting objects: 100% (841/841), done.
remote: Compressing objects: 100% (351/351), done.
remote: Total 7855 (delta 490), reused 812 (delta 475), pack-reused 7014
Receiving objects: 100% (7855/7855), 1.72 MiB | 7.30 MiB/s, done.
Resolving deltas: 100% (5218/5218), done.
Cloning into '/tmp/chip-spv/hip-testsuite'...
remote: Enumerating objects: 554, done.
remote: Counting objects: 100% (554/554), done.
remote: Compressing objects: 100% (243/243), done.
remote: Total 554 (delta 348), reused 486 (delta 282), pack-reused 0
Receiving objects: 100% (554/554), 954.96 KiB | 9.27 MiB/s, done.
Resolving deltas: 100% (348/348), done.
Submodule path 'HIP': checked out '673b51f161758b1d8af2ce49b427eec295c62255'
Submodule 'tests/catch/external/Catch2' (git@github.com:catchorg/Catch2.git) registered for path 'HIP/tests/catch/external/Catch2'
Cloning into '/tmp/chip-spv/HIP/tests/catch/external/Catch2'...
remote: Enumerating objects: 35232, done.
remote: Counting objects: 100% (460/460), done.
remote: Compressing objects: 100% (270/270), done.
remote: Total 35232 (delta 229), reused 385 (delta 190), pack-reused 34772
Receiving objects: 100% (35232/35232), 25.77 MiB | 18.49 MiB/s, done.
Resolving deltas: 100% (24785/24785), done.
Submodule path 'HIP/tests/catch/external/Catch2': checked out '958944d27a2d2fb82aa008377bf4f8752f6b848e'
Submodule path 'bitcode/ROCm-Device-Libs': checked out '11a668963ece50f4a8bd66e65853b796185991bc'
Submodule path 'hip-testsuite': checked out '9b9ebd18fb504a467a5e13a5a3c0a0f926197292'
```

**Comment by zjin-lcf** [comment]
git clone https://github.com/CHIP-SPV/chip-spv.git --recursive
Cloning into 'chip-spv'...
remote: Enumerating objects: 12388, done.
remote: Counting objects: 100% (3229/3229), done.
remote: Compressing objects: 100% (1153/1153), done.
remote: Total 12388 (delta 2209), reused 2743 (delta 2058), pack-reused 9159
Receiving objects: 100% (12388/12388), 9.70 MiB | 16.53 MiB/s, done.
Resolving deltas: 100% (8465/8465), done.
Checking out files: 100% (2364/2364), done.
Submodule 'HIP' (git@github.com:CHIP-SPV/HIP.git) registered for path 'HIP'
Submodule 'bitcode/ROCm-Device-Libs' (https://github.com/RadeonOpenCompute/ROCm-Device-Libs.git) registered for path 'bitcode/ROCm-Device-Libs'
Submodule 'hip-testsuite' (https://github.com/CHIP-SPV/hip-testsuite.git) registered for path 'hip-testsuite'
Cloning into 'HIP'...
The authenticity of host 'github.com (140.82.114.4)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
ECDSA key fingerprint is MD5:7b:99:81:1e:4c:91:a5:0d:5a:2e:2e:80:13:3f:24:ca.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.114.4' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:CHIP-SPV/HIP.git' into submodule path 'HIP' failed

**Comment by zjin-lcf** [comment]
> Hmm strange. Where does "/path/to/chip-spv/HIP" come from I wonder?
> 
> ```
> pvelesko@jlselogin4:/tmp> git clone https://github.com/CHIP-SPV/chip-spv.git --recursive
> Cloning into 'chip-spv'...
> remote: Enumerating objects: 12384, done.
> remote: Counting objects: 100% (3225/3225), done.
> remote: Compressing objects: 100% (1149/1149), done.
> remote: Total 12384 (delta 2208), reused 2743 (delta 2058), pack-reused 9159
> Receiving objects: 100% (12384/12384), 9.70 MiB | 17.42 MiB/s, done.
> Resolving deltas: 100% (8464/8464), done.
> Submodule 'HIP' (git@github.com:CHIP-SPV/HIP.git) registered for path 'HIP'
> Submodule 'bitcode/ROCm-Device-Libs' (https://github.com/RadeonOpenCompute/ROCm-Device-Libs.git) registered for path 'bitcode/ROCm-Device-Libs'
> Submodule 'hip-testsuite' (https://github.com/CHIP-SPV/hip-testsuite.git) registered for path 'hip-testsuite'
> Cloning into '/tmp/chip-spv/HIP'...
> remote: Enumerating objects: 45889, done.
> remote: Counting objects: 100% (633/633), done.
> remote: Compressing objects: 100% (482/482), done.
> remote: Total 45889 (delta 197), reused 566 (delta 149), pack-reused 45256
> Receiving objects: 100% (45889/45889), 17.53 MiB | 21.45 MiB/s, done.
> Resolving deltas: 100% (32010/32010), done.
> Cloning into '/tmp/chip-spv/bitcode/ROCm-Device-Libs'...
> remote: Enumerating objects: 7855, done.
> remote: Counting objects: 100% (841/841), done.
> remote: Compressing objects: 100% (351/351), done.
> remote: Total 7855 (delta 490), reused 812 (delta 475), pack-reused 7014
> Receiving objects: 100% (7855/7855), 1.72 MiB | 7.30 MiB/s, done.
> Resolving deltas: 100% (5218/5218), done.
> Cloning into '/tmp/chip-spv/hip-testsuite'...
> remote: Enumerating objects: 554, done.
> remote: Counting objects: 100% (554/554), done.
> remote: Compressing objects: 100% (243/243), done.
> remote: Total 554 (delta 348), reused 486 (delta 282), pack-reused 0
> Receiving objects: 100% (554/554), 954.96 KiB | 9.27 MiB/s, done.
> Resolving deltas: 100% (348/348), done.
> Submodule path 'HIP': checked out '673b51f161758b1d8af2ce49b427eec295c62255'
> Submodule 'tests/catch/external/Catch2' (git@github.com:catchorg/Catch2.git) registered for path 'HIP/tests/catch/external/Catch2'
> Cloning into '/tmp/chip-spv/HIP/tests/catch/external/Catch2'...
> remote: Enumerating objects: 35232, done.
> remote: Counting objects: 100% (460/460), done.
> remote: Compressing objects: 100% (270/270), done.
> remote: Total 35232 (delta 229), reused 385 (delta 190), pack-reused 34772
> Receiving objects: 100% (35232/35232), 25.77 MiB | 18.49 MiB/s, done.
> Resolving deltas: 100% (24785/24785), done.
> Submodule path 'HIP/tests/catch/external/Catch2': checked out '958944d27a2d2fb82aa008377bf4f8752f6b848e'
> Submodule path 'bitcode/ROCm-Device-Libs': checked out '11a668963ece50f4a8bd66e65853b796185991bc'
> Submodule path 'hip-testsuite': checked out '9b9ebd18fb504a467a5e13a5a3c0a0f926197292'
> ```

It is just my local path (e.g. /home/user/chip-spv/HIP)

**Comment by pvelesko** [comment]
not sure what is going on here. Maybe you need to add your ssh key to github? The repo is public. Can you check if if you can clone it via `git clone https://github.com/CHIP-SPV/HIP.git`

**Comment by pvelesko** [comment]
Fixed. If resolved, please close the issue @zjin-lcf

**Comment by zjin-lcf** [comment]
Submodule path 'HIP': checked out '3c683e1b3b1bf8d42a6778f2ed41504aba36a4b8'
Submodule 'tests/catch/external/Catch2' (git@github.com:catchorg/Catch2.git) registered for path 'HIP/tests/catch/external/Catch2'
Cloning into '/home/user/chip-spv/HIP/tests/catch/external/Catch2'...
fatal: Could not read from remote repository.

**Comment by pvelesko** [comment]
@zjin-lcf ok that should have been the last one, try now.

**Comment by zjin-lcf** [comment]
Thanks
