### ISSUE TITLE
Output of the hipInfo program

### ISSUE THREAD

**Issue by zjin-lcf** [CHIP-SPV/chip-spv#89]
The values "multiProcessorCount, maxThreadsPerMultiProcessor, warpSize" are not the same using OpenCL and Level0 backends on Intel DevCloud.

OpenCL:
```
CHIP warning [TID 887554] [1659643269.953287497] : CHIP_BE was not set. Defaulting to OPENCL

--------------------------------------------------------------------------------
device#                           0
Name:                             Intel(R) UHD Graphics P630 [0x3e96]
pciBusID:                         16
pciDeviceID:                      64
multiProcessorCount:              24
maxThreadsPerMultiProcessor:      10
isMultiGpuBoard:                  0
clockRate:                        1200 Mhz
memoryClockRate:                  1 Mhz
memoryBusWidth:                   256
clockInstructionRate:             2.465 Mhz
totalGlobalMem:                   50.10 GB
maxSharedMemoryPerMultiProcessor: 0.00 GB
totalConstMem:                    4294959104
sharedMemPerBlock:                64.00 KB
regsPerBlock:                     64
warpSize:                         0
....
```

Level0
```
CHIP warning [TID 887678] [1659643337.135896406] : Ignoring alignment. Using hardcoded value 0x1000
CHIP warning [TID 887678] [1659643337.135936619] : Usigned zeMallocHost instead of zeMallocShared due to outstanding bug

--------------------------------------------------------------------------------
device#                           0
Name:                             M
pciBusID:                         16
pciDeviceID:                      64
multiProcessorCount:              8
maxThreadsPerMultiProcessor:      56
isMultiGpuBoard:                  0
clockRate:                        1200 Mhz
memoryClockRate:                  0 Mhz
memoryBusWidth:                   64
clockInstructionRate:             1.2 Mhz
totalGlobalMem:                   50.10 GB
maxSharedMemoryPerMultiProcessor: 0.00 GB
totalConstMem:                    53794992128
sharedMemPerBlock:                64.00 KB
regsPerBlock:                     4096
warpSize:                         32
...
```

**Comment by franz** [comment]
The `maxThreadsPerMultiProcessor:      10` is hardcoded in OpenCL backend, because there is no way to get that information in OpenCL (at least i don't know of any).

I have added a partial fix for the other two (those are bugs), but in general you can only expect to see information we get from the APIs. In some cases the API won't have any information, or the numbers won't match.

**Comment by zjin-lcf** [comment]
Could

> The `maxThreadsPerMultiProcessor: 10` is hardcoded in OpenCL backend, because there is no way to get that information in OpenCL (at least i don't know of any).
> 
> I have added a partial fix for the other two (those are bugs), but in general you can only expect to see information we get from the APIs. In some cases the API won't have any information, or the numbers won't match.

Do you think the attribute is needed in OpenCL ? If so, may you make a feature request ?  Thanks.

**Comment by pvelesko** [comment]
@franz I am confused about your calculation. Why not return `CL_DEVICE_MAX_WORK_GROUP_SIZE` here? @Kerilk

**Comment by franz** [comment]
i'm not sure what you mean. "warp size" in CUDA speak is "subgroup size" in OpenCL. "workgroup size" in OpenCL is "thread block size" in CUDA. Warp size (subgroup size) is fixed in CUDA but not in OpenCL. The only change is that it now returns maximum; it's debatable what's the correct value (IIRC intel supports 8,16 & 32), but the min_element was actually returning zero (there's a zero in the list of values returned by intel driver).

**Comment by pvelesko** [comment]
@franz I was talking about max threads per multi processor. I agree on warp size

**Comment by franz** [comment]
Max threads per multiprocessor has nothing to do with max workgroup size, it's a hardware detail not exposed by OpenCL and not really required for anything (except perhaps performance tuning). [Here](https://stackoverflow.com/questions/43897824/why-is-max-threads-per-multiprocessor-1536-on-my-compute-capability-2-0-gpu) is some explanation for Nvidia. AMD's GPUs work in a similar way but the number is 10, see [here.](https://en.wikipedia.org/wiki/Graphics_Core_Next#Wavefront). For Intel, in Level0 i think the correct value is `numThreadsPerEU` from `ze_device_properties_t` but AFAIK there's no way to get it in OpenCL (unless there's some vendor extension).
