### ISSUE TITLE
More intelligence to the platform initialization

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#93]
Now the BE defaults to OpenCL and if it fails (e.g. no OpenCL drivers installed), it actually gets stuck. It could quite easily try also L0 as a fallback?

**Comment by franz** [comment]
@pjaaskel @Kerilk if chip-spv is run on a machine with both backends available, shall we prefer Level0 or OpenCL ? @pvelesko are you aware of any differences in the provided functionality between the backends ?

**Comment by Kerilk** [comment]
On Aurora we will need to default to Level-Zero. Once we develop a multiplexing strategy switching at runtime will be possible, so the default platform selection will have to be reevaluated anyway.

**Comment by pvelesko** [comment]
fixed in #123
