### ISSUE TITLE
[HIP] hipcc.pl assumes Clang++ is always called 'clang++'

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#96]
This is not the case with the default LLVM binary packages for Debian/Ubuntu, which has the major version number appended (for example _clang++-14_).

**Comment by pjaaskel** [comment]
Not by default (it seems) as it's common to use multiple different versions in the same system.

**Comment by linehill** [comment]
There is a symlink to `clang++` but the `clang++` itself resides in `/usr/lib/llvm-14/bin/` [[source]](https://packages.ubuntu.com/jammy/i386/clang-14/filelist).

**Comment by pjaaskel** [comment]
Symlink to clang++-14 to be accurate. Paulius was hoping there would be a clang++ symlink since the script assumes the executable to be called 'clang++'. Perhaps this can be set up with the 'update-alternatives' mechanism of Ubuntu, but I think a more robust way is to refer to the exact path of the Clang++ binary to be used since there are major incompatibilities between versions.

**Comment by pvelesko** [comment]
> but I think a more robust way is to refer to the exact path of the Clang++
Current `HIP_CLANG_PATH` refers to the directory path where it will look for `clang++` I will make the change to for `HIP_CLANG_PATH` to require a full path to the binary.

**Comment by pvelesko** [comment]
I'm out of the office today and most of tomorrow, FYI

**Comment by pvelesko** [comment]
I think the best solution for Ubuntu would be to create symlinks yourself. In the next release HIP-COMMON will be migrating to the C++ based hipcc so it doesn't make sense to invest time in fixing this perl script and then waiting for AMD to merge changes.

Currently HIPAMD also expects `clang++`

**Comment by pvelesko** [comment]
HIP_CLANG_PATH

**Comment by pjaaskel** [comment]
OK, it would be good to at least document this in README.md or even check in cmake time?

**Comment by pvelesko** [comment]
I will make a note in README.md
